# Generated by Django 5.1.5 on 2025-08-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster', models.URLField(max_length=500)),
                ('rating', models.FloatField(default=0.0)),
                ('year', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Длина в минутах')),
                ('genres', models.ManyToManyField(related_name='movies', to='main.genre')),
            ],
        ),
    ]
