# Generated by Django 5.1.5 on 2025-08-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
