# Generated by Django 5.1.5 on 2025-08-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='video/processed/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='processed_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='processed_status',
            field=models.CharField(choices=[('uploaded', 'Загружено'), ('processing', 'Обрабатывается'), ('processed', 'Обработано'), ('error', 'Ошибка')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
