# Generated by Django 5.1.5 on 2025-08-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_movie_processed_file_movie_processed_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='videos/originals/'),
        ),
    ]
