# Generated by Django 5.1.5 on 2025-08-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_movie_isserial_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(help_text='Страна', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='isSerial',
            field=models.BooleanField(default=False, help_text='Это сериал?'),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasons_count', models.PositiveIntegerField(default=1)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series_info', to='main.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(default=1)),
                ('episode_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Длина в минутах', null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='videos/originals/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='video/processed/')),
                ('processed_status', models.CharField(choices=[('uploaded', 'Загружено'), ('processing', 'Обрабатывается'), ('processed', 'Обработано'), ('error', 'Ошибка')], default='uploaded', max_length=20)),
                ('processed_progress', models.IntegerField(default=0)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='main.series')),
            ],
        ),
    ]
