# Generated by Django 5.1.5 on 2025-08-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_movie_country_alter_movie_isserial_series_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='processed_file',
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='main.movie'),
        ),
    ]
