# Generated by Django 5.1.5 on 2025-08-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_episode_processed_file_alter_episode_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'Эпизод', 'verbose_name_plural': 'Эпизоды'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='processed_file',
        ),
    ]
