# Generated by Django 5.1.5 on 2025-08-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_episode_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Длина в минутах', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Длина в минутах', null=True),
        ),
    ]
